// +build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
)

var header = `// Auto generated by gen_stop.go, DO NOT EDIT

package nlp

var StopWords = map[string]bool{
`

func main() {
	fmt.Print(header)
	s := bufio.NewScanner(os.Stdin)
	for s.Scan() {
		if len(s.Text()) == 0 || s.Text()[0] == '#' {
			continue
		}
		fmt.Printf("%q: true,\n", s.Text())
	}

	if err := s.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %s", err)
		os.Exit(1)
	}
	fmt.Println("}")
}
